services:
  postgres:
    image: postgres:latest
    container_name: meu-container
    environment:
      POSTGRES_DB: meAjudeDB
      POSTGRES_USER: meAjude
      POSTGRES_PASSWORD: meAjude
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: